---
 - hosts: server
   remote_user: bob
   tasks:
     - name: Ensure repository is set
       apt: name= state=latest
       become: yes
 # System update
     - name: Ensure all 
       apt: 
         name: '*'
         state: latest
       become: yes
       tags: update

         
