---
version: '2'

networks:
  default:
    driver: bridge

volumes: 
  vol_nginx:

#networks:
#  net_nginx


services:
  web: 
    container_name: web
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - /Docker/web/www:/var/www/html
      - /Docker/web/sites:/etc/nginx/conf.d

  PHP:
    container_name: PHP
    image: php-mysql:fpm
    volumes:
      - /Docker/web/www/:/var/www/html

  mariadb:
    container_name: mariadb
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      default:
        aliases:
           - db
#  nginx:
#    image: nginx
#    container_name: nginx
#    volumes:
#      - vol_nginx: /var/www
#    environment:
#      - VARIABLE=truc
#    ports:
#      - "88:80"
 #   networks: name=net_nginx 
    

