--- 
 - name: "[web]-install"
   hosts: web
   remote_user: bob
   
   vars:
      user: dem
      domains:
         - domain: "{{ item }}"
           php: no
           repo: https://github.com/nassafou/sitesy.git
         - domain: "{{ item }}"
           php: yes
         
        

   roles:
     - common
     - user
     - nginx
