---
 - name: "[web]- installation"
   hosts: web
   remote_user: bob

   vars:
     user: johnd
     domains: 
        - domain: local.dev 
          php: no

        - domain:  demo.fr
          php: yes

   roles: 
     - common
     - user
     - nginx
