---
  # installation nginx
 - name: "[WEB]- Install nginx "
   become: yes 
   apt: name=nginx state=latest
  
 # start ngnix
 - name: "[web]- start nginx "
   become: yes 
   service: name=nginx state=started enabled=true

 # supprimer la configuration
 - name: "[web]- suppression"
   become: yes
   file: path=/etc/nginx/sites-enabled/default state=absent
   notify: nginx reload

 - name: "[web] install PHP"
   become: yes
   include: php.yml
  
 # inclusion de la partie site.yml
 - name: "[web]- site"
   become: yes
   include: site.yml
   with_items: domains
  

