---
 # construction de nginx install de base
 - name: "[web]- intallation ngnix"
   become: yes
   apt: name=nginx state=latest

 - name: "[web] - start"
   become: yes
   service: name=nginx state=started enabled=true

 #suppression de nginx pour changer emplacement
 - name: Supprimer default.conf
   become: yes
   file: path=/etc/nginx/sites-enabled/default state=absent
   notify: nginx reload
 #création de nouveau domain de nginx qui sera activé et son emplacement dans le home
 - name: creation du dossier
   become: yes 
   file: path=/home/{{ user }}/{{ domain }} state=directory owner={{ user }}
 #création de symbolique le dossier www
 - name: Lien vers www
   become: yes
   file: src=/home/{{ user }}/{{ domain }} dest=/var/www/{{ domain }} state=link

# après le dossier passons à la configuration de nginx injection de fichier par template
 - name: "[web]Création de la configuration nginx"
   become: yes
   template: src=templates/nginx.j2 dest=/etc/nginx/sites-available/{{ domain }}
# activation du domain
 - name: "[web] Activation du domain {{ domain }}"
   become: yes
   file: src=/etc/nginx/sites-available/{{ domain }} dest=/etc/nginx/sites-enabled/{{ domain }} state=link
   notify: nginx reload
