---
 - name: "[web]-Ajout de dotdeb au repo "
   apt_repository: repo='{{ item}}'
   with_items: 
      - deb http://packages.dotdeb.org wheezy all
      - deb-src http://packages.dotdeb.org wheezy al

 - name: "[web] -Ajout de clef dotdeb"
   apt_key: url=https://www.dotdeb.org/dotdeb.gpg

 - name: "[web] APT update"
   apt: update_cache=yes

 - name: "[web] Installation de PHP"
   apt: name={{ item }} state=latest
   with_items: php_packages
 
# - name: "[web] - desable dangerous fonction"

 - lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='disable_functions[\s]?=' line='disable_functions = exec,passthru,shell_exec,proc_open,popen'     
 - lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='post_max_size[\s]?=' line='post_max_size={{ post_max_size}}'
 - lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='upload_max_filesize[\s]?=' line='upload_max_filesize={{ upload_max_filesize}}'        
 - lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='memory_limit[\s]?=' line='memory_limit={{ memory_limite}}'        
 - lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='date.time_zone[\s]?=' line='date.timezone={{date.timezone}}'     
   notify: php restart   
