---
# tasks file for roles/nginx
 - name: "[web]-install nginx "
   become: yes
   apt: name=nginx # state=latest

 - name: "[web] -start"
   become: yes
   service: name=nginx state=started enabled=yes

 - name: "[web] -delete nginx file "
   become: yes
   file: path=/etc/nginx/sites-enabled/default state=absent
   notify: nginx reload

 - name: "[web] -create domain"
   become: yes
   file:   path=/home/{{ user }}/{{ domain }} state=directory owner={{ user }}

 - name: "[web] -link www"
   file: src=/home/{{ user }}/{{ domain }} dest=/var/www/{{ domain }} state=link

 - name: "[web] -config "
   become: yes
   template: src=/templates/nginx.j2  dest=/etc/nginx/sites-available/{{ domain }}

 - name: "[web] -conf activate"
   become: yes 
   file: src=/etc/nginx/sites-available/{{ domain }} dest=/etc/nginx/sites-enabled/{{ domain }} state=link


