---
 - name: "[mariadb]-install "
   hosts: mariadb
   remote_user: bob
#   vars:
#      user: volibear
#      domain: dev.local

   roles:
#     - common
#     - user
#     - nginx
     - mariadb
     - collect
 
 - name: "[central]- install"
   remote_user: bob
   hosts: central
   roles: 
     - central
