---
# tasks file for user

 - name: "Create user"
   become: yes
   when: user is defined
   user: name="{{ item}}"  comment="utilisateur" shell=/usr/bin/sh
   with_items:
       - denis
       - bea 

 - name: "[web] - set authorized key taken from file"
   when: user is defined
   authorized_key: user={{ item }} key="{{ lookup( 'file', '~/.ssh/id_rsa.pub' )}}" state=present


