---
# tasks file for user

 - name: "Create user"
   become: yes
   when: user is defined
   user: name="{{ item}}"  comment="utilisateur" shell=/usr/bin/sh
   with_items:
       - denis
       - bea 
