# Set Hostname
- name: Ensure hostname is set
  hostname:
    name: "{{ hostname.short }}.{{ hostname.domain }}"

# Define banners
- name: Define banners
  template:
    src: "motd"
    dest: "/etc/motd"
    owner: root
    group: root
    mode: 0644
