---
# tasks file for roles/nginx
 - name: "[web] install nginx"
   become: yes
   apt: name=nginx #state=latest

 - name: "[web] started nginx"
   service: name=nginx state=started enabled=true

 - name: "[web] delete nginx"
   become: yes
   file: path=/etc/nginx/sites-enabled/default state=absent
   notify: nginx reload

 - name: "[web] config"
   become: yes
   file: path=/home/{{ user }}/{{ domain }} state=directory owner={{ user }}

 - name: "[web] link www"
   become: yes
   file: src=/home/{{ user }}/{{ domain }} dest=/var/www/{{ domain }} state=link

# - name: "[web] - available "
#   become: yes
#   file: src=/home/{{ user }}/{{ domain }} dest=/etc/nginx/sites-available/{{ domain }}

 - name: "[web] injection du fichier du serveur web nginx "
   become: yes
   template: src=templates/nginx.j2  dest=/etc/nginx/sites-available/{{ domain }}

 - name: "[web] activation du serveur web"
   become: yes
   file: src=/etc/nginx/sites-available/{{ domain }} dest=/etc/nginx/sites-enabled/{{ domain }} state=link
   notify: nginx reload

